### ISSUE TITLE
As an LA I want to know which scheme's spend-to-date I am changing

### ISSUE THREAD

**Issue by Sparrow0hawk** [acteng/update-your-capital-schemes#144]
_As an LA I want to know which scheme's spend-to-date I am changing so that I don't inadvertently update the wrong one._

**Comment by markhobson** [comment]
Could use a [question caption](https://design-system.service.gov.uk/patterns/question-pages/#section-headings-question-pages-example-open) to show the scheme name:

![image](https://github.com/user-attachments/assets/626c58c2-614e-4842-8248-4f4699f99612)
